[project]
name = "sd-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy==1.26.3",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "xformers>=0.0.30",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128"
