max_train_steps = 7500
#learning_rate = 0.0001
#learning_rate = 1e-4
learning_rate = 1e-4
#text_encoder_lr = 5e-6
cache_text_encoder_outputs = true
network_train_unet_only = true
metadata_description = "recommended tags: hoge"
# キャラクター用
network_dim = 32
network_alpha = 32
# 絵柄用
#network_dim = 128
#network_alpha = 128
output_name = "hoge_v1.0"
#save_every_n_steps = 500
sample_every_n_steps = 250
#shuffle_caption = true
#keep_tokens = 1
train_batch_size = 1
gradient_checkpointing = true
noise_offset_type = "Original"
min_snr_gamma = 5

# 以下、eps-pred用
noise_offset = 0.0357

# 以下、v-pred用
#v_parameterization = true
#scale_v_pred_loss_like_noise_pred = true
#noise_offset = 0.0
